//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisSistemi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsatis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblsatis()
        {
            this.tblsatisdetay = new HashSet<tblsatisdetay>();
        }
    
        public int id { get; set; }
        public Nullable<int> personel_id { get; set; }
        public Nullable<int> musteri_id { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> odeme_sekli { get; set; }
        public Nullable<double> toplam_tutar { get; set; }
        public Nullable<double> odenen { get; set; }
        public Nullable<double> kalan { get; set; }
        public Nullable<int> sil_id { get; set; }
        public Nullable<System.DateTime> ekleme_tarihi { get; set; }
        public Nullable<System.DateTime> guncelleme_tarihi { get; set; }
    
        public virtual tblmusteri tblmusteri { get; set; }
        public virtual tblpersonel tblpersonel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblsatisdetay> tblsatisdetay { get; set; }
    }
}
