//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisSistemi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsatisdetay
    {
        public int id { get; set; }
        public Nullable<int> satis_id { get; set; }
        public Nullable<int> urun_id { get; set; }
        public Nullable<double> birimfiyat { get; set; }
        public Nullable<double> miktar { get; set; }
        public Nullable<double> toplamfiyat { get; set; }
        public Nullable<int> sil_id { get; set; }
        public Nullable<System.DateTime> ekleme_tarihi { get; set; }
        public Nullable<System.DateTime> guncelleme_tarihi { get; set; }
    
        public virtual tblsatis tblsatis { get; set; }
        public virtual tblurun tblurun { get; set; }
    }
}
