//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisSistemi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblusers
    {
        public int id { get; set; }
        public Nullable<int> personel_id { get; set; }
        public string kullanici_adi { get; set; }
        public string sifre { get; set; }
        public Nullable<int> sil_id { get; set; }
    }
}
